version: '3.8' # Версия Docker Compose

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: my_hr_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-my_hr_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-my_hr_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-my_hr_user} -d ${DB_NAME:-my_hr_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис Go-приложения
  app:
    build: .
    container_name: my_hr_app_container
    restart: on-failure 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-my_hr_user}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_NAME: ${DB_NAME:-my_hr_db}
      DB_SSLMODE: "disable"
    ports:
      - "8080:8080"

volumes:
  pgdata: